{% set version = '0.9.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-crew
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/crew_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/crew/crew_{{ version }}.tar.gz
  sha256: d3bef8fcec3142fc5c00f8e399c9214deed9a7168a9e597c99ecc84965d3e19d

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6
    - r-cli >=3.1.0
    - r-data.table
    - r-getip
    - r-later
    - r-mirai >=0.12.0
    - r-nanonext >=0.12.0
    - r-processx
    - r-promises
    - r-ps
    - r-rlang
    - r-tibble
    - r-tidyselect
  run:
    - r-base
    - r-r6
    - r-cli >=3.1.0
    - r-data.table
    - r-getip
    - r-later
    - r-mirai >=0.12.0
    - r-nanonext >=0.12.0
    - r-processx
    - r-promises
    - r-ps
    - r-rlang
    - r-tibble
    - r-tidyselect

test:
  commands:
    - $R -e "library('crew')"           # [not win]
    - "\"%R%\" -e \"library('crew')\""  # [win]

about:
  home: https://wlandau.github.io/crew/
  dev_url: https://github.com/wlandau/crew
  license: MIT
  summary: In computationally demanding analysis projects, statisticians and data scientists
    asynchronously deploy long-running tasks to distributed systems, ranging from traditional
    clusters to cloud services. The 'NNG'-powered 'mirai' R package by Gao (2023) <https://CRAN.R-project.org/package=mirai>
    is a sleek and sophisticated scheduler that efficiently processes these intense
    workloads. The 'crew' package extends 'mirai' with a unifying interface for third-party
    worker launchers. Inspiration also comes from packages. 'future' by Bengtsson (2021)
    <doi:10.32614/RJ-2021-048>, 'rrq' by FitzJohn and Ashton (2023) <https://github.com/mrc-ide/rrq>,
    'clustermq' by Schubert (2019) <doi:10.1093/bioinformatics/btz284>), and 'batchtools'
    by Lang, Bischel, and Surmann (2017) <doi:10.21105/joss.00135>.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - brendanf

# Package: crew
# Title: A Distributed Worker Launcher Framework
# Description: In computationally demanding analysis projects, statisticians and data scientists asynchronously deploy long-running tasks to distributed systems, ranging from traditional clusters to cloud services. The 'NNG'-powered 'mirai' R package by Gao (2023) <https://CRAN.R-project.org/package=mirai> is a sleek and sophisticated scheduler that efficiently processes these intense workloads. The 'crew' package extends 'mirai' with a unifying interface for third-party worker launchers. Inspiration also comes from packages. 'future' by Bengtsson (2021) <doi:10.32614/RJ-2021-048>, 'rrq' by FitzJohn and Ashton (2023) <https://github.com/mrc-ide/rrq>, 'clustermq' by Schubert (2019) <doi:10.1093/bioinformatics/btz284>), and 'batchtools' by Lang, Bischel, and Surmann (2017) <doi:10.21105/joss.00135>.
# Version: 0.9.0
# License: MIT + file LICENSE
# URL: https://wlandau.github.io/crew/, https://github.com/wlandau/crew
# BugReports: https://github.com/wlandau/crew/issues
# Authors@R: c( person( given = c("William", "Michael"), family = "Landau", role = c("aut", "cre"), email = "will.landau.oss@gmail.com", comment = c(ORCID = "0000-0003-1878-3253") ), person( given = "Daniel", family = "Woodie", role = "ctb" ), person( family = "Eli Lilly and Company", role = "cph" ))
# Depends: R (>= 4.0.0)
# Imports: cli (>= 3.1.0), data.table, getip, later, mirai (>= 0.12.0), nanonext (>= 0.12.0), processx, promises, ps, R6, rlang, stats, tibble, tidyselect, tools, utils
# Suggests: knitr (>= 1.30), markdown (>= 1.1), rmarkdown (>= 2.4), testthat (>= 3.0.0)
# Encoding: UTF-8
# Language: en-US
# VignetteBuilder: knitr
# Config/testthat/edition: 3
# RoxygenNote: 7.3.1
# NeedsCompilation: no
# Packaged: 2024-02-07 13:38:50 UTC; C240390
# Author: William Michael Landau [aut, cre] (<https://orcid.org/0000-0003-1878-3253>), Daniel Woodie [ctb], Eli Lilly and Company [cph]
# Maintainer: William Michael Landau <will.landau.oss@gmail.com>
# Repository: CRAN
# Date/Publication: 2024-02-08 05:30:02 UTC
